### ISSUE TITLE
Docker-container only runs on x86_64 architectures

### ISSUE THREAD

**Issue by 1nfiniteloop** [dockhippie/alpine#2]
# Issue
Container only runs on **x86_64** architecture since the binary `usr/bin/templater` is "hardwired" into the git repo and used for all architectures when building container.

# Suggested solution
How about to make the container architecture agnostic and instead fetch the correct binary version of "templater" when building the container as example below? 

in `Dockerfile`:
```bash
RUN curl -o /usr/bin/templater https://dl.webhippie.de/templater/master/templater-0.0.0-master-$(uname -o)-$(uname -m) && chmod +x /usr/bin/templater
```

The name of "templater" is not following the convention according to `$(uname -m)` though;
`templater-0.0.0-master-linux-arm-6` vs 
`templater-0.0.0-master-linux-armv6l`

**Comment by tboerger** [comment]
So far I have built all the images for amd64 only... When I start to migrate the build process to Drone I will prepare it as multi architecture including a manifest.

**Comment by tboerger** [comment]
I'm building multi manifests now for amd64, arm64v8 and arm32v6.
